/**
 * Authentication service for token validation and user management
 */

import { HttpClient } from "../utils/http-client";
import { ApiClient } from "../api";
import { CacheService } from "./cache.service";
import {
  UserInfo,
  AuthStrategy,
  LoginResponse,
  LogoutResponse,
  RefreshTokenResponse,
} from "../types/config.types";
import type { ExchangeTokenResponse } from "../api/types/auth.types";
import { handleAuthErrorSilent, isHttpStatus } from "./auth-error-handler";
import {
  createEnvTokenClient,
  extractTokenFromEnvResponse,
  fetchEnvironmentTokenResponse,
} from "./auth-environment-token";
import {
  clearTokenCache as clearTokenCacheHelper,
  clearUserCache as clearUserCacheHelper,
  extractUserIdFromToken,
  getTokenCacheKey,
} from "./auth-cache-helpers";
import { extractErrorInfo } from "../utils/error-extractor";
import { logErrorWithContext } from "../utils/console-logger";
import {
  buildAuthStrategyWithToken,
  getCachedUserInfo,
  cacheUserInfo,
  getCachedTokenValidation,
  cacheTokenValidation,
  mapUserInfo,
  generateCorrelationId,
} from "./auth.service.helpers";

export class AuthService {
  private httpClient: HttpClient;
  private apiClient: ApiClient;
  private cache: CacheService;
  private tokenValidationTTL: number;
  private minValidationTTL: number;
  private userTTL: number;

  constructor(
    httpClient: HttpClient,
    apiClient: ApiClient,
    cache: CacheService,
  ) {
    this.cache = cache;
    this.httpClient = httpClient;
    this.apiClient = apiClient;
    const config = this.httpClient.config;
    this.tokenValidationTTL = config.cache?.tokenValidationTTL || 900; // 15 minutes default
    this.minValidationTTL = config.cache?.minValidationTTL || 60; // 60 seconds default
    this.userTTL = config.cache?.userTTL || 300; // 5 minutes default
  }

  /**
   * Check if token matches configured API key for testing
   * @private
   */
  private isApiKeyToken(token: string): boolean {
    const config = this.httpClient.config;
    return config.apiKey !== undefined && token === config.apiKey;
  }

  /**
   * Get environment token using client credentials.
   * Never throws from service layer. Logs details and returns safe fallback on failure.
   * @returns Environment token string; empty string when the token cannot be obtained.
   */
  async getEnvironmentToken(): Promise<string> {
    const correlationId = generateCorrelationId(this.httpClient.config.clientId);
    const clientId = this.httpClient.config.clientId;
    const axiosTimeout = 4000;

    try {
      const { tempAxios, timeoutId, controller } = await createEnvTokenClient(
        this.httpClient.config,
        axiosTimeout,
        clientId,
      );
      const response = await fetchEnvironmentTokenResponse(
        tempAxios,
        timeoutId,
        controller,
        this.httpClient.config.clientTokenUri || "/api/v1/auth/token",
        axiosTimeout,
      );
      const token = extractTokenFromEnvResponse(response.data);
      if (response.status >= 200 && response.status < 300 && token) {
        return token;
      }
      handleAuthErrorSilent(
        new Error(`Invalid response format. Status: ${response.status}`),
        "Get environment token",
        correlationId,
        clientId,
      );
      return "";
    } catch (error) {
      handleAuthErrorSilent(
        error,
        "Get environment token",
        correlationId,
        clientId,
      );
      return "";
    }
  }

  /**
   * Initiate login flow by calling controller. Returns login URL and state for browser redirect.
   * Your app only needs to know your own URLs and miso-controller - it handles OAuth callbacks with Keycloak.
   * @param params - Login parameters
   * @param params.redirect - Final destination URL in your app after authentication (e.g., 'https://myapp.com/dashboard')
   * @param params.state - Optional CSRF protection token (auto-generated by controller if omitted)
   * Never throws from service layer. Logs details and returns fallback response on failure.
   * @returns Login response with loginUrl and state; returns `success: false` and empty login URL on error.
   */
  async login(params: {
    redirect: string;
    state?: string;
  }): Promise<LoginResponse> {
    const correlationId = generateCorrelationId(this.httpClient.config.clientId);
    const clientId = this.httpClient.config.clientId;

    try {
      // Use ApiClient for typed API call
      const authStrategy = this.httpClient.config.authStrategy;
      const response = await this.apiClient.auth.login(
        { redirect: params.redirect, state: params.state },
        authStrategy,
      );

      // Convert ApiClient response format to service response format
      return {
        success: response.success,
        data: {
          loginUrl: response.data.loginUrl,
          state: response.data.state || "",
        },
        timestamp: response.timestamp,
      };
    } catch (error) {
      handleAuthErrorSilent(error, "Login", correlationId, clientId);
      return {
        success: false,
        data: { loginUrl: "", state: params.state || "" },
        timestamp: new Date().toISOString(),
      };
    }
  }

  /**
   * Validate token with controller
   * Caches validation results by token hash with smart TTL based on token expiration
   * If API_KEY is configured and token matches, returns true without calling controller
   * @param token - User authentication token
   * @param authStrategy - Optional authentication strategy override
   * Never throws from service layer. Returns false when validation cannot be completed.
   * @returns True if token is valid; false otherwise or on error.
   */
  async validateToken(
    token: string,
    authStrategy?: AuthStrategy,
  ): Promise<boolean> {
    // Check API_KEY bypass for testing
    if (this.isApiKeyToken(token)) {
      return true;
    }

    try {
      // Generate cache key using token hash (security - no userId exposure)
      const cacheKey = getTokenCacheKey(token);

      const cached = await getCachedTokenValidation(this.cache, cacheKey);
      if (cached !== null) return cached;

      // Cache miss - fetch from controller using ApiClient
      const authStrategyWithToken = buildAuthStrategyWithToken(
        token,
        authStrategy,
        this.httpClient.config.authStrategy,
      );

      const result = await this.apiClient.auth.validateToken(
        { token },
        authStrategyWithToken,
      );

      const authenticated = result.data?.authenticated || false;

      await cacheTokenValidation(
        this.cache,
        cacheKey,
        token,
        authenticated,
        this.tokenValidationTTL,
        this.minValidationTTL,
      );

      return authenticated;
    } catch (error) {
      this.logAuthServiceError(
        "Validate token",
        error,
        token,
        "/api/auth/validate",
      );
      return false;
    }
  }

  /**
   * Get user information from token.
   * If API_KEY is configured and token matches, returns null (by design for testing).
   * @param token - User authentication token.
   * @param authStrategy - Optional authentication strategy override.
   * Never throws from service layer. Returns null on failures.
   * @returns User info when available; otherwise null.
   */
  async getUser(
    token: string,
    authStrategy?: AuthStrategy,
  ): Promise<UserInfo | null> {
    // Check API_KEY bypass for testing - return null by design
    if (this.isApiKeyToken(token)) {
      return null;
    }

    try {
      const authStrategyWithToken = buildAuthStrategyWithToken(
        token,
        authStrategy,
        this.httpClient.config.authStrategy,
      );

      const result = await this.apiClient.auth.validateToken(
        { token },
        authStrategyWithToken,
      );

      if (result.data?.authenticated && result.data.user) {
        return mapUserInfo(result.data.user);
      }

      return null;
    } catch (error) {
      this.logAuthServiceError("Get user", error, token, "/api/auth/validate");
      return null;
    }
  }

  private logAuthServiceError(
    operation: string,
    error: unknown,
    token: string,
    path: string,
    method: "GET" | "POST" = "POST",
  ): void {
    const userId = extractUserIdFromToken(token);
    const errorInfo = extractErrorInfo(error, {
      endpoint: path,
      method,
      correlationId: (error as { correlationId?: string })?.correlationId,
    });
    const suffix = userId ? ` (userId: ${userId})` : "";
    errorInfo.message = `${operation} failed${suffix}: ${errorInfo.message}`;
    logErrorWithContext(errorInfo, "[AuthService]");
  }

  /**
   * Get user information from GET /api/v1/auth/user endpoint
   * Caches user info by userId with configurable TTL (default 5 minutes)
   * If API_KEY is configured and token matches, returns null (by design for testing)
   * @param token - User authentication token
   * @param authStrategy - Optional authentication strategy override
   * Never throws from service layer. Returns null on failures.
   * @returns User info when available; otherwise null.
   */
  async getUserInfo(
    token: string,
    authStrategy?: AuthStrategy,
  ): Promise<UserInfo | null> {
    // Check API_KEY bypass for testing - return null by design
    if (this.isApiKeyToken(token)) {
      return null;
    }

    try {
      // Extract userId from token to check cache first (avoids API call on cache hit)
      const userId = extractUserIdFromToken(token);
      const cacheKey = userId ? `user:${userId}` : null;
      const cached = await getCachedUserInfo(this.cache, cacheKey);
      if (cached) return cached;

      // Cache miss - fetch from controller
      const authStrategyWithToken = buildAuthStrategyWithToken(
        token,
        authStrategy,
        this.httpClient.config.authStrategy,
      );

      const result = await this.apiClient.auth.getUser(authStrategyWithToken);

      if (result.data?.authenticated && result.data.user) {
        const user = mapUserInfo(result.data.user);
        await cacheUserInfo(this.cache, cacheKey, user, this.userTTL);
        return user;
      }

      return null;
    } catch (error) {
      this.logAuthServiceError(
        "Get user info",
        error,
        token,
        "/api/auth/user",
        "GET",
      );
      return null;
    }
  }

  /**
   * Clear cached token validation result
   * Uses token hash for cache key (always clears regardless of token structure)
   * @param token - User authentication token
   */
  clearTokenCache(token: string): void {
    clearTokenCacheHelper(this.cache, token);
  }

  /**
   * Clear cached user info
   * Uses userId extracted from token for cache key
   * @param token - User authentication token
   */
  clearUserCache(token: string): void {
    clearUserCacheHelper(this.cache, token);
  }

  /**
   * Logout user. Gracefully handles no active session (400). Clears token/user caches.
   * @param params - Logout parameters with token to invalidate
   * Never throws from service layer. Returns fallback failure payload on unexpected errors.
   * @returns Logout response with success status/message; 400/no-session is treated as successful logout.
   */
  async logout(params: { token: string }): Promise<LogoutResponse> {
    const correlationId = generateCorrelationId(this.httpClient.config.clientId);
    const clientId = this.httpClient.config.clientId;

    try {
      // Use ApiClient for typed API call
      const response = await this.apiClient.auth.logoutWithToken(params.token);

      // Clear caches after successful logout
      this.clearTokenCache(params.token);
      this.clearUserCache(params.token);

      return response;
    } catch (error) {
      // Gracefully handle 400 Bad Request (no session, already logged out, etc.)
      if (isHttpStatus(error, 400)) {
        // eslint-disable-next-line no-console -- Architecture-approved auth service warning log
        console.warn(
          `[Auth] Logout: No active session (400) [${correlationId}]`,
          { correlationId },
        );
        this.clearTokenCache(params.token);
        this.clearUserCache(params.token);
        return {
          success: true,
          message: "Logout successful (no active session)",
          timestamp: new Date().toISOString(),
        };
      }
      handleAuthErrorSilent(error, "Logout", correlationId, clientId);
      return {
        success: false,
        message: "Logout failed",
        timestamp: new Date().toISOString(),
      };
    }
  }

  /**
   * Refresh user access token using refresh token
   * @param refreshToken - Refresh token to exchange for new tokens
   * Never throws from service layer. Returns null on failure.
   * @returns New access/refresh token payload when successful; otherwise null.
   */
  async refreshToken(
    refreshToken: string,
    authStrategy?: AuthStrategy,
  ): Promise<RefreshTokenResponse | null> {
    const correlationId = generateCorrelationId(this.httpClient.config.clientId);
    const clientId = this.httpClient.config.clientId;

    try {
      // Use ApiClient for typed API call
      const authStrategyToUse =
        authStrategy || this.httpClient.config.authStrategy;
      const response = await this.apiClient.auth.refreshToken(
        { refreshToken },
        authStrategyToUse,
      );

      // Convert ApiClient response format to service response format
      if (response.data) {
        return {
          success: response.success,
          accessToken: response.data.accessToken,
          refreshToken: response.data.refreshToken || refreshToken,
          expiresIn: response.data.expiresIn,
          expiresAt: response.timestamp,
          timestamp: response.timestamp,
        };
      }

      return null;
    } catch (error) {
      return handleAuthErrorSilent(
        error,
        "Refresh token",
        correlationId,
        clientId,
      );
    }
  }

  /**
   * Exchange external user token (e.g. Entra) for Keycloak token.
   * Uses client token only; no client id/secret sent to controller.
   * @param token - External token (e.g. Entra) to exchange
   * @param authStrategy - Optional authentication strategy override
   * Never throws from service layer. Returns fallback payload on failure.
   * @returns Exchange response with accessToken and tokenExchanged flag.
   */
  async exchangeUserToken(
    token: string,
    authStrategy?: AuthStrategy,
  ): Promise<ExchangeTokenResponse> {
    const correlationId = generateCorrelationId(this.httpClient.config.clientId);
    const clientId = this.httpClient.config.clientId;

    try {
      return await this.apiClient.auth.exchangeUserToken(
        { token },
        authStrategy,
      );
    } catch (error) {
      handleAuthErrorSilent(
        error,
        "Exchange user token",
        correlationId,
        clientId,
      );
      return {
        success: false,
        data: {
          accessToken: "",
          tokenExchanged: false,
        },
        timestamp: new Date().toISOString(),
      };
    }
  }

  /**
   * Check if user is authenticated (has valid token)
   * @param token - User authentication token
   * @param authStrategy - Optional authentication strategy override
   * Never throws from service layer. Returns false on validation errors.
   * @returns True when token is considered authenticated; otherwise false.
   */
  async isAuthenticated(
    token: string,
    authStrategy?: AuthStrategy,
  ): Promise<boolean> {
    return this.validateToken(token, authStrategy);
  }
}
